### ISSUE TITLE
Update netrunning compendiums

### ISSUE THREAD

**Issue by OctarineSourcerer** [OctarineSourcerer/cyberpunk2020#101]
Thus far, there have been Netrunning Equipment and Netrunning Program compendiums, using the catch-all Misc type of item. Now that there are those item types in the `cyberdecks` branch, we can update the compendiums to be the full `cyberdeck` and `program` item types where applicable.

**Comment by TaladPS** [comment]
Programs were already done in my previous commit.
Cyberdecks are now done with this one: https://github.com/OctarineSourcerer/cyberpunk2020/pull/102

**Comment by OctarineSourcerer** [comment]
Yep, works for me!
