### ISSUE TITLE
Still melee weapons don't work (

### ISSUE THREAD

**Issue by JohBalalaika** [OctarineSourcerer/cyberpunk2020#109]
Why doesn't the attacks from the weapon fencing skill work?
![1](https://user-images.githubusercontent.com/96943142/150697243-7172b925-1fba-4fda-a770-ba84d1a23f45.JPG)
here are the weapon settings.
no throws are displayed in the chat. 
If I put a different type of attack, then either nothing happens or the skill of fencing is not taken into account in the throw Q_Q
please help me solve the problem.
I'm tired of reinstalling Foundry every time on version 8.
with the updated version on 0.3.2  of the 2020 system, the problem does not disappear.

**Comment by OctarineSourcerer** [comment]
Hi @JohBalalaika! Sorry about that - in the update to 9, an in-the-middle-of-things change had slipped through the cracks and broke melee weapon rolling. It should be fixed in `0.3.3`, could you let me know if that works for you?

**Comment by JohBalalaika** [comment]
Yes, everything is working properly now, thank you very much. ^_^
