### ISSUE TITLE
Autofire Shows 'undefined' for Hit Location

### ISSUE THREAD

**Issue by BaronVonCram** [OctarineSourcerer/cyberpunk2020#110]
Prior to the version 9 update autofire calculated hit location for shots that hit based on the to-hit roll versus DC. After the update the version 9 autofire presents hit locations as undefined in chat, though it still supplies damage. This occurs regardless of modules loaded, the version 9 screen shots were taken in safe mode.

Looking at the console logs this issue may be related to issue #108. 

![Autofire 0 8 9](https://user-images.githubusercontent.com/65889012/151676996-a02c98ed-5854-4a82-9002-fc13ee2e5cc7.jpg)
![Autofire 9v245](https://user-images.githubusercontent.com/65889012/151676993-69a0996b-e305-4360-aaca-9b7ab32c9676.jpg)
![Autofire 9v245 Console output](https://user-images.githubusercontent.com/65889012/151676995-c0fffd96-56c5-4d1e-9b9c-5d3ba56a54c4.jpg)

**Comment by OctarineSourcerer** [comment]
Good catch, thanks! Should be fixed in 0.3.4 :) Reminded me that roll terms weren't showing properly in multihits - that was in the development branch, but I've brought it over in this update too.
