### ISSUE TITLE
Creating a New Character on V10 Causes The Skill List to be Empty

### ISSUE THREAD

**Issue by ElPresidentePoole** [OctarineSourcerer/cyberpunk2020#120]
Essentially the title.

In Foundry v10, with the latest git release ([292140e](https://github.com/OctarineSourcerer/cyberpunk2020/commit/292140eab7bb85fbe92dd88309ffd8318159aa1e)) of this system, creating a character results in a character with no skills.

![image](https://user-images.githubusercontent.com/39707978/192433990-52573fe6-cdd0-4c3c-a90e-945362cf6561.png)

**Comment by ElPresidentePoole** [comment]
After a lot of trial and error I found out this is actually not OctarineSourcerer's fault, but rather something to do with how I was git-ing it.  I made a separate folder named cyberpunk2020-git and changed the name in system.json to match, but that somehow caused this bug.  My bad!

**Comment by OctarineSourcerer** [comment]
> After a lot of trial and error I found out this is actually not OctarineSourcerer's fault, but rather something to do with how I was git-ing it. I made a separate folder named cyberpunk2020-git and changed the name in system.json to match, but that somehow caused this bug. My bad!

No worries! This actually _was_ a bug... until three days ago https://github.com/OctarineSourcerer/cyberpunk2020/commit/3fba0f9a449947fbbd3bdce005f18046955ba3dd, and I only found that one out while I was sorting out v10 migration in a hurry. So you weren't actually wrong per se!
