### ISSUE TITLE
Dragging items onto a token's sheet doesn't add item to inventory

### ISSUE THREAD

**Issue by CeSiumShark** [OctarineSourcerer/cyberpunk2020#126]
Any item added seems to not be added to the inventory, here I added a random pistol to a sheet, and the weight value seems off.
![image](https://github.com/OctarineSourcerer/cyberpunk2020/assets/30117392/3eed3362-273c-4b02-a461-9cab9d5e32f2)
This is hard to show in picture but the combat tab isn't updated either, it's simply blank. Adding armor also seems to break the SP values. 
![image](https://github.com/OctarineSourcerer/cyberpunk2020/assets/30117392/b5622174-0d71-46a0-8160-6c3918167b11)
I added a kevlar vest here, changing the torso value to 010 and the other values to 00.

This happens to every token I spawn, importing the item doesn't work either and results in the same issues. For some reason this doesn't happen to a friend's game I played in, I downgraded to his version though and the same issues arose.

Here's a list of errors I found in the console log: 
![image](https://github.com/OctarineSourcerer/cyberpunk2020/assets/30117392/f8796c33-e6bd-414b-8e9b-70eefc5df569)
![image](https://github.com/OctarineSourcerer/cyberpunk2020/assets/30117392/d6b2e382-1413-4202-b3c5-cfe65d9110ed)

[miami.zip](https://github.com/OctarineSourcerer/cyberpunk2020/files/12021562/miami.zip)
Here's the world I'm using, even without any of the modules the issue still occurs.

**Comment by OctarineSourcerer** [comment]
Should be fixed as of v0.3.8 :)
