### ISSUE TITLE
Chipped skills roll as zero

### ISSUE THREAD

**Issue by RAVANAZAR** [OctarineSourcerer/cyberpunk2020#128]
Foundry 11.308 
When marking a skill as "chipped" the character sheet shows the skill value change but when rolling the skill the dice roll in chat adds 0 to the roll rather than the new chipped value.

**Comment by RAVANAZAR** [comment]
Works like a charm. Thank you for all your work on this. We use it often.  We are playing Cybergeneration v1 and the kids skills are at half strength vs. adults but full strength vs. other kids.  Marking the skill chipped lets us toggle between full and half value.

**Comment by OctarineSourcerer** [comment]
> Works like a charm. Thank you for all your work on this. We use it often. We are playing Cybergeneration v1 and the kids skills are at half strength vs. adults but full strength vs. other kids. Marking the skill chipped lets us toggle between full and half value.

That's fantastic to hear! This being on the backburner - and not being in a CP2020 campaign - means this project often passes my mind, but little bits like this make me very happy with what I've made thus far.
