### ISSUE TITLE
Foundry tries to update to ver 0.3.10.

### ISSUE THREAD

**Issue by R0gu3P403n1x** [OctarineSourcerer/cyberpunk2020#144]
As the title says, my foundry keeps saying an update to v 0.3.10 is available, but then cannot find it.  I can't seem to find it either, so I don't know where it is getting it's information.

**Comment by OctarineSourcerer** [comment]
Oops, that one was my bad! There should now be a v0.3.10 for it to try downloading. Let me know if that works?

**Comment by R0gu3P403n1x** [comment]
That got it.  Thanks!

**Comment by OctarineSourcerer** [comment]
Awesome, glad to hear it.
