### ISSUE TITLE
Stun/Deathsave 

### ISSUE THREAD

**Issue by drowzero0** [OctarineSourcerer/cyberpunk2020#40]
This is something which does not have any urgency

it works like it should and shows the stun/deathsave and the treshholds.
but wen a character is not in "mortal" state it should not show a value since it could confuse rolling players.
since your description says roll bellow, it doesnt count for equal rolls.

![image](https://user-images.githubusercontent.com/62395017/114656088-bb63e380-9ced-11eb-8f9f-613747933240.png)

**Comment by OctarineSourcerer** [comment]
Sorted out in f2c03a8
