### ISSUE TITLE
Choosing Role for Actorsheet

### ISSUE THREAD

**Issue by drowzero0** [OctarineSourcerer/cyberpunk2020#42]
the "Role" tab is just a textfield which allows to write everything into it.
![image](https://user-images.githubusercontent.com/62395017/114656952-472a3f80-9cef-11eb-80e2-fb57013eb041.png)

a Dropdown with the Predefined Classes would be easier to use.
also some stat/skillrolls could be made dependent on the class.
like if you have class "Solo" take "Combat sense" into account when rolling "Awareness notice"

**Comment by OctarineSourcerer** [comment]
I'm aware it's a textbox - at the moment, this is pretty much so people can use roles I haven't seen or written yet (I think there are a bunch in sourcebooks I haven't read). So for now, it can be anything, and if you want the Solo's stuff, you can just put some points in Combat Sense - those should still apply no matter what Role you are.

Once I have a grip on all the roles that are out there, I'm likely to make this a dropdown, and have an option in the config to hide other-role special skills in the skills tab.

**Comment by OctarineSourcerer** [comment]
As no role skills are added by default to an actor, and the role skills they need can be added/removed at will, I'm thinking to keep this a textbox for flexibility's sake. In the case of Combat Sense etc, the skill's taken into account if it's there

It may be worth adding a warning for if an Actor has a role but no role skills though.

If Roles do some things that are more than skills though, feel free to reopen this.
