### ISSUE TITLE
Skill sorting - keep the set filter

### ISSUE THREAD

**Issue by drowzero0** [OctarineSourcerer/cyberpunk2020#56]
in my session yesterday it got a bit timeconsuming since i had to re-set the filter to "sort by STAT" every time i changed from another tab inside the sheet back to the skill.tab
is it possible to keep this setting inside the character/token when switching tabs, or even after reopening a actorsheet?
i personally prefer the sort by stat view since its closer to the real actorsheet design.

**Comment by drowzero0** [comment]
i just upgraded to 0.2.1 and guess you already fixed that.
so never mind. if i happen to find this problem again i will check if there are any logfiles and send them over. 
but so long i just close this again.
sorry for the wrong alert.

**Comment by OctarineSourcerer** [comment]
No worries at all :)
