### ISSUE TITLE
Feature - Combat Roll successstats for diffrent distances

### ISSUE THREAD

**Issue by drowzero0** [OctarineSourcerer/cyberpunk2020#57]
when rolling with a weapon it is possible to choose the distance you are firing from.
in my examplescreen a federated Arms X9mm:
![image](https://user-images.githubusercontent.com/62395017/115159388-2d904b80-a093-11eb-90a8-6e2232e158db.png)

it would be nice if the needed successrate gets shown in the dicewindow:
pointblank = 10
close =15
medium =20
long =25
extreme =30

this would make the use of the range more interesting.
in my session yesterday everyone just rolled for pointblank since it makes no diffrence.

**Comment by OctarineSourcerer** [comment]
Good point! This actually does show if you use autofire, even though it's a much more basic template. I'll add it in.

**Comment by OctarineSourcerer** [comment]
Should be sorted in a892f37, in develop branch at the moment. Is a basic addition, but shows the to-hit DC for the range chosen in the attack :)
