### ISSUE TITLE
Sync between tokens/actorsheets and over diffrent scenes

### ISSUE THREAD

**Issue by drowzero0** [OctarineSourcerer/cyberpunk2020#58]
I noticed that sometimes the sync of items between an actor and an actor.token is not happening.
this also shows up for woundtracking. i had a few players yesterday that told me they tracked their wounds but it didnt show up in the actor.sheet but only in the token.
also when changing the scene all wounds get deleted from the actor.sheets.
the wounds remain on the token on the just left scene but the actorsheets are reseted.

**Comment by OctarineSourcerer** [comment]
Okay so I've seen this elsewhere in Foundry. Token sheets are actually independent copies of actor sheets - this is useful for mooks who may be several copies of a single enemy, but not for player characters, which you're seeing here.

If you go to the token's settings, there should be a checkbox that says "link data with actor" or something like that. Be warned that clicking this will prefer the *actor* data, so anything just on the token will be erased. From that point on, changes for that token should also apply to its Actor. It's a Foundry thing, not this system I think, but it *is* annoying. 

Try checking that box and see if that fixes things for you :) if you want it to apply to all tokens made of an Actor, open the Actor sheet, and at its top click "prototype token". These are the default settings for any token of this actor, so ticking the same box there will make it so any of its future tokens will be connected to the Actor sheet. 

If that *doesn't* fix things I'm happy to look into it further, but I'm 90% sure this is a FoundryVTT thing.

**Comment by OctarineSourcerer** [comment]
Hmm. So I went to check on this a little, and found a bug, being tracked here https://github.com/OctarineSourcerer/cyberpunk2020/issues/59
Hopefully will get that fixed for you so you can actually try this without Foundry dying on you.

**Comment by OctarineSourcerer** [comment]
Both that bug and this should be fixed in 3f7dc37d41662061753f60ed2a01a87ff69edcf2 :)
When your world migrates to 0.2.2, all character actors should, by default, have any further tokens linked to them (you might have to use new tokens for this to take effect). Any new characters created will also have this option sorted.
As a bonus, all character tokens should now have vision too by default!
