### ISSUE TITLE
Positive Feedback - Great work of implementations

### ISSUE THREAD

**Issue by drowzero0** [OctarineSourcerer/cyberpunk2020#60]
i just want to let you know. the work you are doing is GREAT!
my Group (6 Players and a few watching persons) love the new setting you gave us.
we earlier played on another plattform which we didnt host ourself. but now, the game is running so smooth.
but what everyone really loves is the designs and sheets you created.
all those sheets are great in my oppinion and this is also the feedback i got from my players.

since i dont know where to post feedback on thse fixed issues i will do an full mentioning of every feature there is so far which i really got to love and also loved to see the evolution of those in the past days! (it really goes on damn fast)

1st actorsheet - skills.tab:
![image](https://user-images.githubusercontent.com/62395017/115262043-74824d80-a134-11eb-97ef-e156961e917a.png)

everything works so smooth!
stats get changed by increasing wounds.
skills are sortable by name or stat and there is also a nice filter working like a charm.
the math behind stats and statdepending skills works as it should also those extra "stats" like leap, run, lift and carry.

2nd actorsheet -combat.tab:
![image](https://user-images.githubusercontent.com/62395017/115262366-c3c87e00-a134-11eb-9a3c-302d85f22937.png)
initiative gets rolled and summarized correctly but still not counting for "battles".
the stun/deathsafe works really great if you klick it:
![image](https://user-images.githubusercontent.com/62395017/115262741-1a35bc80-a135-11eb-93ab-51a83499457e.png)

the correct summarization of gear is still a thing to be done, but the image itself and the correct calculation of incumbrance is damn good, love it!
being able to roll those weapons is the most charming part of this site:
your reworked "roll-sheet" is awesome. looks much more tidied up.
![image](https://user-images.githubusercontent.com/62395017/115263025-5bc66780-a135-11eb-9756-5543ccf32a24.png)

3rd actorsheet - Gear.tab:
4 types of items! awesome!
![image](https://user-images.githubusercontent.com/62395017/115263211-86182500-a135-11eb-8b20-84ffc15a3dc7.png)
drag and drop into the sheet is possible, that is soooo nice!
you can roll your weapons even from the gear.tab by clicking on the image! wohooo!
my players are loving this!

Gearsheets:
![image](https://user-images.githubusercontent.com/62395017/115263459-bbbd0e00-a135-11eb-85fc-ea073a4c3f1d.png)
great stuff! and you already implemented those "actively worn- booleans" and cost/weight fields! nice one!

Overall i can just go on and on! it is a great work!

**Comment by OctarineSourcerer** [comment]
<3 Thank you so much! That honestly means a lot - I went into this without having ever made something for Foundry before, and having avoided web development for a long time, and so for people to be actually enjoying it is amazing!

Future development might a little slower, as I should really get on with some other work I've been procrastinating, but I fully intend to keep adding to this :) 

(am sad I'll have to close this issue by the way :'( Thank you again!)
