### ISSUE TITLE
Some little problems

### ISSUE THREAD

**Issue by spidercourgan** [OctarineSourcerer/cyberpunk2020#62]
The value for leaping isn't correct. On the sheet leaping is MA div. by 4 and not running div. by 4, as it is written in the rulebook,

Automatic weapons: a possibility for single shot is missing.

**Comment by OctarineSourcerer** [comment]
Ah yes, you're right! Adjusted the LEAP value in 6fbe7c6. 
As for automatic weapons, the book says specifically that there are 3 ways to use an auto weapon: 
![image](https://user-images.githubusercontent.com/6842867/115556597-c1873080-a2a8-11eb-8c49-b4f5331c41ed.png)

Single fire isn't included there, and if it hadn't said "there are 3 ways to use an auto weapon" and then listed 3rb, suppressive and full auto I'd be inclined to agree.

**Comment by WildBillLives** [comment]
In real life the overwhelming majority of automatic weapons are capable of single shot fire (you will see selector switches on virtually every automatic small arm showing 'safe', 'semi', and 'auto' settings). For what its worth, I speak from experience as I was an armorer in the Navy for a number of years and have extensive experience with and knowledge of firearms.

**Comment by OctarineSourcerer** [comment]
> In real life the overwhelming majority of automatic weapons are capable of single shot fire (you will see selector switches on virtually every automatic small arm showing 'safe', 'semi', and 'auto' settings). For what its worth, I speak from experience as I was an armorer in the Navy for a number of years and have extensive experience with and knowledge of firearms.

Huh, that's pretty neat! I'll add a single-shot option to the full auto :)

**Comment by OctarineSourcerer** [comment]
Cool, both these things should be sorted now, and are in today's release (I know releases are small and rapid here, but I've got a particularly dense block of time soon I won't be able to develop this much in, so I want to make sure this is available).
