### ISSUE TITLE
using Melee weapons with correct attack mode

### ISSUE THREAD

**Issue by drowzero0** [OctarineSourcerer/cyberpunk2020#65]
when rolling on melee.skilltype weapons it uses the same sheet after a klick as when rolling for a ranged.skilltype weapon.

![image](https://user-images.githubusercontent.com/62395017/115969096-8ea89b00-a53b-11eb-885b-3540f4898557.png)
in the screen above i created a cyberarm-punching to use it while rolling for a melee attack with it.
the attacktype "martial" makes no diffrence as when picking "mono".

the Attack modifier sheet should not show range, aiming and fire mode.

also the modifications for fast-draw, hipfire and riccochet are not making sense for melee, 
if you are not shooting your fist at your targets.

also in this case the rolling is not dependent on the range roll-caps to reach, which you just implemented for "range" (that works great for ranged weapons)

**Comment by OctarineSourcerer** [comment]
Ah yeah, at the moment melee has a long way to go, and for now just uses the same attack-modifiers dialog to at least ensure some kinds of attacks are possible. You're right though, it should be quite different! It's on the list ;) And I mean the whole martial arts thing is on the list, punching, kicking, the whole works eventually.

**Comment by OctarineSourcerer** [comment]
As a slight update, melee's going to be getting a little love soon. There's essentially going to be, for melee weapons:
* regular melee. pick a non-martial-arts skill, bash.
* martial arts. you _don't_ have to pick a skill here, as the idea behind martial arts will be essentially a "use my martial arts" weapon, where you choose which technique to do, and which martial art you're using.
* mono. bit like regular melee, but will let me put the special mono rules in later on if needed

**Comment by OctarineSourcerer** [comment]
This should be sorted in the `develop` branch now with commit 8fae929 (well, that and the ones leading up to it). A fair few things were rummaged about underneath the hood, but that should be mostly sorted, both for melee weapons (attackType: melee) and martial arts (attackType: martial). Note that martial arts attacks are done by having an actor with a weapon item that has the martial attackType.

The way martial weapons work is their attackSkill doesn't actually matter - once you roll with them, you choose a martial art to go with (this doesn't at the moment confer the martial art's bonus, you'll have to do that yourself for now). Let me know how it goes!

One thing that's *definitely* missing as it stands is martial arts' key moves/bonuses, but that's being tracked at #69.
