### ISSUE TITLE
Automatic Fire not adding REF attribute,

### ISSUE THREAD

**Issue by Emilio1922** [OctarineSourcerer/cyberpunk2020#66]
When using an automatic weapon on autofire it's possible to roll numbers under the shooters REF at point blank, which shouldn't be possible. I don't think this applies to burst fire, as I haven't rolled under REF despite trying a few dozen times.
![Autofire](https://user-images.githubusercontent.com/32806614/117391706-8434bc80-aebe-11eb-82e5-814b40cba4e2.PNG)
It would also be nice to see all modifiers applied to burst and auto rolls like they're shown for semi auto to be sure it's applying everything correctly.

**Comment by OctarineSourcerer** [comment]
This _is_ possible if your weapon accuracy is negative, as weapon accuracy is included in the modifiers. Could you check that your SMG's accuracy is higher than -3 I think? 

Still, went and checked this out. Made a full auto roll, stole the resulting formula that was being used with Full Auto, point blank, reflex 4, weapon accuracy 0, 0 in the relevant weapon skill. Asked foundry to roll x1000:
![image](https://user-images.githubusercontent.com/6842867/117436831-56d02900-af27-11eb-8c60-70cd74a12e69.png)

It takes reflex into account for sure on my end, I suspect either your weapon accuracy is super low or there's another negative modifier on there - I'd be curious about that. If that's not the case, something's wacky and I'll look further into it :) Let me know, and I'll close the issue or keep it open as applies.

This issue being raised *does* stem from modifiers not being visible in autofire as they are with other rolls. The autofire card was thrown together as a prototype and hasn't yet been updated (though that *will* be done, and I've set up an issue at https://github.com/OctarineSourcerer/cyberpunk2020/issues/67 to track).

**Comment by Emilio1922** [comment]
I don't think there's any negative modifiers being applied, but here's the sheet, weapon sheet, and another sub 5 roll.
![Autofire](https://user-images.githubusercontent.com/32806614/117512268-4aff5980-af5d-11eb-84bb-857c2c2e0ee7.PNG)
The Submachinegun skill is also set to zero and is set to reflexes not chipped skill.

**Comment by OctarineSourcerer** [comment]
> I don't think there's any negative modifiers being applied, but here's the sheet, weapon sheet, and another sub 5 roll.
> The Submachinegun skill is also set to zero and is set to reflexes not chipped skill.

Huh, that is _weird_, you're right. There are a couple ways I can check this (especially if you're on the `develop` branch), but I'm currently doing a bit of work to make the autofire chat card actually include modifiers, so if you don't want to use the develop branch, it might be easiest if I get that sorted and then we can use that to figure this out. If yo _are_ cool with using the develop branch, I can quickly throw some log statements in there to pin this down :)

I do know that in one of the older versions it would apply a -1 penalty per 10 bullets fired at any range that wasn't close, but it shouldn't for point-blank in the latest versions.

**Comment by Emilio1922** [comment]
I'm not on the develop branch, and the chat card having modifiers displayed would be great anyway. That said the issue is repeatable so I'd assume using the in game roller rather than the formula it's intended to pull from would probably net you similar results.
As far as the -1 at any range that isn't close, I don't think that applies. The first roll posted a photo for was a 3 which would require a -3 assuming the minimum roll of 1 with the 5 REF being included. I also made sure I was using the latest version on foundry and there was no update, so I don't think the -1 is an issue anyway.

**Comment by OctarineSourcerer** [comment]
Okay, that's fine. There should be a new version published just now! It adds vehicles, and a bit of the styling for autofire (including the modifiers list). That's not complete - there are a couple under-the-hood changes I want to make for showing *all* rolls in this system before I finish it, and I'm likely to trim +0 modifiers in future, but it should help here a little. Wanna try with that? :)

**Comment by Emilio1922** [comment]
Yeah, it's got a 30 round auto and is adding the -1 for each 10 for a total of -3, which in hindsight makes sense and I forgot to take it into account in my previous comment.

So the -1 is still applying to point-blank range, but is working properly for all other ranges.

**Comment by OctarineSourcerer** [comment]
So, I was a Very Silly Dev and had made it check for if it was equal to `ranges.pb` instead of `ranges.pointBlank`, so while I'd thought I'd implemented a check, that check didn't work. 

The hotfix should now be in the release, in commit 4ea04be. A hotfix like this isn't enough to warrant a whole new release I think, but I don't know if foundry has something like "redownload system". In any case, next time you download the system, it should be in there.

**Comment by Emilio1922** [comment]
Awesome, thanks for the quick fix.

**Comment by OctarineSourcerer** [comment]
And thank you for letting me know about it! :)
