### ISSUE TITLE
Cost at items needs more space

### ISSUE THREAD

**Issue by drowzero0** [OctarineSourcerer/cyberpunk2020#73]
if you display 4 digits at the Cost field for items it gets shown nice and good to read.
but if you start with more expensive items like cars which can easily go to 6 and more digits it gets hard to read
here an example with a car with a 5 digit price:
![image](https://user-images.githubusercontent.com/62395017/119813899-1b9f9500-beea-11eb-9434-e484170fb774.png)

**Comment by OctarineSourcerer** [comment]
Should be sorted in 456f3c150432a73f2f6ea7f40437d5e0992afbd3
