### ISSUE TITLE
Item Name  - Space

### ISSUE THREAD

**Issue by drowzero0** [OctarineSourcerer/cyberpunk2020#74]
Items get their name in the top bar as "tabname" and below as "itemname" 
in the "itemname" line you also show for weapons auto | pistol or for armor head|torso|etc.
i would say that this is not needed, since you can see the information just a few lines below:
to get a long name fully shown you have to pull your windows like this:
(screen shows the items full name, and how it looks "freshly" opened)

![image](https://user-images.githubusercontent.com/62395017/119814509-c31cc780-beea-11eb-9a60-ac28745b8714.png)

if it would just show the itemtype that would be enough. like weapon, armor, vehicle misc or cyberwear.

**Comment by OctarineSourcerer** [comment]
This is I believe fixed in the current version. It's still a bit of an issue in the combat tab, but I'll have to do something scrollable there, as it *does* need to show roughly what the armour covers
