### ISSUE TITLE
Weapon attack rolls chat message has [object Object] apparently as the dice

### ISSUE THREAD

**Issue by TheWing** [OctarineSourcerer/cyberpunk2020#90]
![image](https://user-images.githubusercontent.com/922569/128790997-f8bd4a59-b113-48fd-907d-63bc4f43def3.png)

It seems the autofire results in chat show these gray [object Object] texts instead of the results of the rolls. Or after looking at the page source, it seems these are for the rolls that don't get rolled due to the weapon not having higher rate of fire?
![image](https://user-images.githubusercontent.com/922569/128791220-82f80c17-6815-4e0f-b39f-fc0aea8403df.png)

Not really that critical for actual gameplay since the values are there, but these should probably be filtered out so as to not cause confusion.

**Comment by OctarineSourcerer** [comment]
Sorry for the late responses! I've been juggling all sorts, so haven't done anything on this for a while.

That being said, I'll go fix that! Much as it's not a gamebreaker, it definitely definitely shouldn't be there, and I try to prioritise bugs where I can.

PS: Anything you'd super love to see added? I can see myself getting more busy and not able to add much for the future, but if there's anything I can reasonably sort out in the rare bits of free dev time, I'd be happy to

**Comment by OctarineSourcerer** [comment]
Should be sorted in 02115e2 :)

**Comment by TheWing** [comment]
Hi.

No worries with the speed of development, it's not like there'd be a rush. Glad to see it be a rather simple fix in the end!

As far as things I'd like to see further down the line, I'd like character sheets for Programs, AIs and Cyberdecks for use in Netrunning; Basically the sheets on p.135, along with some very simple sheets for the programs. AI-sheets could be a simplified version of the NPC sheet, basically with only skills and life.
Netrunning works surprisingly well with the tile-system of foundry, so these sheets would just smooth things out from the DM perspective.

I'll probably open some issues if I come up with a more concrete idea of what these should look like :)
